/* CREACIÓN DE DATOS */

DROP DATABASE IF EXISTS utn_proyecto;
CREATE DATABASE utn_proyecto ;

USE utn_proyecto ;

/* CREACIÓN DE TABLAS */

CREATE TABLE ESTUDIANTE(
ID_ESTUDIANTE INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_EST VARCHAR(100) NOT NULL,
APELLIDO_EST VARCHAR(100) NOT NULL,
FECHA_NAC DATE NOT NULL,
GENERO VARCHAR(1),
DIRECCION VARCHAR(100),
CORREO_EST VARCHAR(100) UNIQUE NOT NULL,
TEL_EST VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE CURSO(
ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_CUR VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(300),
NIVEL VARCHAR(1) NOT NULL,
DURACION INT NOT NULL
);

CREATE TABLE INSCRIPCION(
ID_INSCRIPCION INT PRIMARY KEY AUTO_INCREMENT,
ID_ESTUDIANTE INT NOT NULL,
ID_CURSO INT NOT NULL,
FECHA_INS DATE NOT NULL,
ESTADO VARCHAR(1) NOT NULL
);

CREATE TABLE NOTA(
ID_NOTA INT PRIMARY KEY AUTO_INCREMENT,
ID_ESTUDIANTE INT NOT NULL,
ID_CURSO INT NOT NULL,
NOTA INT NOT NULL,
FECHA_EV DATE NOT NULL
);

CREATE TABLE PROFESOR(
ID_PROF INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_PROF VARCHAR(100) NOT NULL,
ESPECIALIDAD VARCHAR(100) NOT NULL,
CORREO_PROF VARCHAR(100) UNIQUE NOT NULL,
TEL_PROF VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE ASIGN_PROF(
ID_ASIGNACION INT PRIMARY KEY AUTO_INCREMENT,
ID_CURSO INT NOT NULL,
ID_PROF INT NOT NULL,
HORARIO INT NOT NULL,
AULA_ASIGN INT NOT NULL
);

