USE utn_proyecto ;

SET GLOBAL local_infile = true;

LOAD DATA  LOCAL INFILE '/structure/data-csv/Estudiante_DATA.csv'
INTO TABLE ESTUDIANTE
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NOMBRE_EST
,APELLIDO_EST
,FECHA_NAC
,GENERO
,DIRECCION
,CORREO_EST
,TEL_EST)
;



LOAD DATA  LOCAL INFILE '/structure/data-csv/Curso_DATA.csv'
INTO TABLE CURSO
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(NOMBRE_CUR
, DESCRIPCION
, NIVEL
, DURACION);



LOAD DATA  LOCAL INFILE '/structure/data-csv/Inscripcion_DATA.csv'
INTO TABLE INSCRIPCION
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ID_ESTUDIANTE
,ID_CURSO
,FECHA_INS
,ESTADO) ;



LOAD DATA  LOCAL INFILE '/structure/data-csv/Nota_DATA.csv'
INTO TABLE NOTA
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS 
(ID_ESTUDIANTE
,ID_CURSO
,NOTA
,FECHA_EV);


LOAD DATA  LOCAL INFILE '/structure/data-csv/Profesor_DATA.csv'
INTO TABLE PROFESOR
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS 
(NOMBRE_PROF
, ESPECIALIDAD
, CORREO_PROF
, TEL_PROF);


LOAD DATA  LOCAL INFILE '/structure/data-csv/AsignProf_DATA.csv'
INTO TABLE ASIGN_PROF
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS 
(ID_CURSO
, ID_PROF
, HORARIO
, AULA_ASIGN);

-- -- ESTUDIANTES

ALTER TABLE INSCRIPCION
ADD CONSTRAINT FK_INSCR_EST 
FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE (ID_ESTUDIANTE);

ALTER TABLE INSCRIPCION
ADD CONSTRAINT FK_INSCR_CUR 
FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO);

-- -- NOTAS

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOT_EST 
FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE (ID_ESTUDIANTE);

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOT_CUR 
FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO);

-- ASIGNACIÓN DE PROFES

ALTER TABLE ASIGN_PROF
ADD CONSTRAINT FK_ASIGN_CUR
FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO);

ALTER TABLE ASIGN_PROF
ADD CONSTRAINT FK_ASIGN_PROF 
FOREIGN KEY (ID_PROF) REFERENCES PROFESOR (ID_PROF);
